/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripBuilderRouteImport } from './routes/trip-builder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RewardsIndexRouteImport } from './routes/rewards/index'
import { Route as ItineraryIndexRouteImport } from './routes/itinerary/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as CountryIndexRouteImport } from './routes/$country/index'
import { Route as ItineraryIdRouteImport } from './routes/itinerary/$id'
import { Route as CountryServiceIndexRouteImport } from './routes/$country/$service/index'
import { Route as ItineraryShareTokenRouteImport } from './routes/itinerary/share/$token'
import { Route as CountryServiceIdRouteImport } from './routes/$country/$service/$id'

const TripBuilderRoute = TripBuilderRouteImport.update({
  id: '/trip-builder',
  path: '/trip-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsIndexRoute = RewardsIndexRouteImport.update({
  id: '/rewards/',
  path: '/rewards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryIndexRoute = ItineraryIndexRouteImport.update({
  id: '/itinerary/',
  path: '/itinerary/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryIndexRoute = CountryIndexRouteImport.update({
  id: '/$country/',
  path: '/$country/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryIdRoute = ItineraryIdRouteImport.update({
  id: '/itinerary/$id',
  path: '/itinerary/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryServiceIndexRoute = CountryServiceIndexRouteImport.update({
  id: '/$country/$service/',
  path: '/$country/$service/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryShareTokenRoute = ItineraryShareTokenRouteImport.update({
  id: '/itinerary/share/$token',
  path: '/itinerary/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryServiceIdRoute = CountryServiceIdRouteImport.update({
  id: '/$country/$service/$id',
  path: '/$country/$service/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/trip-builder': typeof TripBuilderRoute
  '/itinerary/$id': typeof ItineraryIdRoute
  '/$country/': typeof CountryIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/itinerary/': typeof ItineraryIndexRoute
  '/rewards/': typeof RewardsIndexRoute
  '/$country/$service/$id': typeof CountryServiceIdRoute
  '/itinerary/share/$token': typeof ItineraryShareTokenRoute
  '/$country/$service/': typeof CountryServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/trip-builder': typeof TripBuilderRoute
  '/itinerary/$id': typeof ItineraryIdRoute
  '/$country': typeof CountryIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/itinerary': typeof ItineraryIndexRoute
  '/rewards': typeof RewardsIndexRoute
  '/$country/$service/$id': typeof CountryServiceIdRoute
  '/itinerary/share/$token': typeof ItineraryShareTokenRoute
  '/$country/$service': typeof CountryServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/trip-builder': typeof TripBuilderRoute
  '/itinerary/$id': typeof ItineraryIdRoute
  '/$country/': typeof CountryIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/itinerary/': typeof ItineraryIndexRoute
  '/rewards/': typeof RewardsIndexRoute
  '/$country/$service/$id': typeof CountryServiceIdRoute
  '/itinerary/share/$token': typeof ItineraryShareTokenRoute
  '/$country/$service/': typeof CountryServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/trip-builder'
    | '/itinerary/$id'
    | '/$country/'
    | '/bookings/'
    | '/itinerary/'
    | '/rewards/'
    | '/$country/$service/$id'
    | '/itinerary/share/$token'
    | '/$country/$service/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/trip-builder'
    | '/itinerary/$id'
    | '/$country'
    | '/bookings'
    | '/itinerary'
    | '/rewards'
    | '/$country/$service/$id'
    | '/itinerary/share/$token'
    | '/$country/$service'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/trip-builder'
    | '/itinerary/$id'
    | '/$country/'
    | '/bookings/'
    | '/itinerary/'
    | '/rewards/'
    | '/$country/$service/$id'
    | '/itinerary/share/$token'
    | '/$country/$service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  TripBuilderRoute: typeof TripBuilderRoute
  ItineraryIdRoute: typeof ItineraryIdRoute
  CountryIndexRoute: typeof CountryIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  ItineraryIndexRoute: typeof ItineraryIndexRoute
  RewardsIndexRoute: typeof RewardsIndexRoute
  CountryServiceIdRoute: typeof CountryServiceIdRoute
  ItineraryShareTokenRoute: typeof ItineraryShareTokenRoute
  CountryServiceIndexRoute: typeof CountryServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip-builder': {
      id: '/trip-builder'
      path: '/trip-builder'
      fullPath: '/trip-builder'
      preLoaderRoute: typeof TripBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards/': {
      id: '/rewards/'
      path: '/rewards'
      fullPath: '/rewards/'
      preLoaderRoute: typeof RewardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/': {
      id: '/itinerary/'
      path: '/itinerary'
      fullPath: '/itinerary/'
      preLoaderRoute: typeof ItineraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/': {
      id: '/$country/'
      path: '/$country'
      fullPath: '/$country/'
      preLoaderRoute: typeof CountryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/$id': {
      id: '/itinerary/$id'
      path: '/itinerary/$id'
      fullPath: '/itinerary/$id'
      preLoaderRoute: typeof ItineraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$service/': {
      id: '/$country/$service/'
      path: '/$country/$service'
      fullPath: '/$country/$service/'
      preLoaderRoute: typeof CountryServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/share/$token': {
      id: '/itinerary/share/$token'
      path: '/itinerary/share/$token'
      fullPath: '/itinerary/share/$token'
      preLoaderRoute: typeof ItineraryShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$service/$id': {
      id: '/$country/$service/$id'
      path: '/$country/$service/$id'
      fullPath: '/$country/$service/$id'
      preLoaderRoute: typeof CountryServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  TripBuilderRoute: TripBuilderRoute,
  ItineraryIdRoute: ItineraryIdRoute,
  CountryIndexRoute: CountryIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  ItineraryIndexRoute: ItineraryIndexRoute,
  RewardsIndexRoute: RewardsIndexRoute,
  CountryServiceIdRoute: CountryServiceIdRoute,
  ItineraryShareTokenRoute: ItineraryShareTokenRoute,
  CountryServiceIndexRoute: CountryServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
