/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItineraryIndexRouteImport } from './routes/itinerary/index'
import { Route as CountryIndexRouteImport } from './routes/$country/index'
import { Route as CountryServiceIndexRouteImport } from './routes/$country/$service/index'
import { Route as CountryServiceIdRouteImport } from './routes/$country/$service/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryIndexRoute = ItineraryIndexRouteImport.update({
  id: '/itinerary/',
  path: '/itinerary/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryIndexRoute = CountryIndexRouteImport.update({
  id: '/$country/',
  path: '/$country/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryServiceIndexRoute = CountryServiceIndexRouteImport.update({
  id: '/$country/$service/',
  path: '/$country/$service/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryServiceIdRoute = CountryServiceIdRouteImport.update({
  id: '/$country/$service/$id',
  path: '/$country/$service/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/$country/': typeof CountryIndexRoute
  '/itinerary/': typeof ItineraryIndexRoute
  '/$country/$service/$id': typeof CountryServiceIdRoute
  '/$country/$service/': typeof CountryServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/$country': typeof CountryIndexRoute
  '/itinerary': typeof ItineraryIndexRoute
  '/$country/$service/$id': typeof CountryServiceIdRoute
  '/$country/$service': typeof CountryServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/$country/': typeof CountryIndexRoute
  '/itinerary/': typeof ItineraryIndexRoute
  '/$country/$service/$id': typeof CountryServiceIdRoute
  '/$country/$service/': typeof CountryServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/$country/'
    | '/itinerary/'
    | '/$country/$service/$id'
    | '/$country/$service/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/$country'
    | '/itinerary'
    | '/$country/$service/$id'
    | '/$country/$service'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/$country/'
    | '/itinerary/'
    | '/$country/$service/$id'
    | '/$country/$service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CountryIndexRoute: typeof CountryIndexRoute
  ItineraryIndexRoute: typeof ItineraryIndexRoute
  CountryServiceIdRoute: typeof CountryServiceIdRoute
  CountryServiceIndexRoute: typeof CountryServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/': {
      id: '/itinerary/'
      path: '/itinerary'
      fullPath: '/itinerary/'
      preLoaderRoute: typeof ItineraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/': {
      id: '/$country/'
      path: '/$country'
      fullPath: '/$country/'
      preLoaderRoute: typeof CountryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$service/': {
      id: '/$country/$service/'
      path: '/$country/$service'
      fullPath: '/$country/$service/'
      preLoaderRoute: typeof CountryServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$service/$id': {
      id: '/$country/$service/$id'
      path: '/$country/$service/$id'
      fullPath: '/$country/$service/$id'
      preLoaderRoute: typeof CountryServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CountryIndexRoute: CountryIndexRoute,
  ItineraryIndexRoute: ItineraryIndexRoute,
  CountryServiceIdRoute: CountryServiceIdRoute,
  CountryServiceIndexRoute: CountryServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
